language: node_js
node_js:
  - "0.10"

services:
  - mongodb
  - rabbitmq
  - elasticsearch

before_script:
  - "curl http://localhost:9200/"
# before_install:
#   - "wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.1.0.deb"
#   - sudo dpkg -i elasticsearch-1.1.0.deb
#   - sudo service elasticsearch start
#   - sleep 5
